# 起動手順
# https://github.com/zelkovascum/Docker-Rails-React/blob/main/memo.md

version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.prod
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    image: rails:dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/myapp
      - ./api/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      # RAILS_ENV: production
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    command: sh -c "cd reactapp && yarn start"
    ports:
      - "8000:3000"
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - api
  web:
    build:
      context: ./nginx/
    # volumes:
    #   - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
volumes:
  mysql-data:
    driver: local
