version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
  test:
    docker:
      - image: cimg/ruby:3.1.2-node
        environment:
          RAILS_ENV: test
      # - image: circleci/mysql:latest
      - image: cimg/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 1m
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: Database setup
          command: |
            bundle exec rails db:create db:migrate
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
